/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ArrayOfRelatedEntriesInner struct {

	// A subject, discipline, or branch of knowledge particular to the Sense
	Domains *Arrayofstrings `json:"domains,omitempty"`

	// The identifier of the word
	Id string `json:"id"`

	// IANA language code specifying the language of the word
	Language string `json:"language,omitempty"`

	// A particular area in which the pronunciation occurs, e.g. 'Great Britain'
	Regions *Arrayofstrings `json:"regions,omitempty"`

	// A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
	Registers *Arrayofstrings `json:"registers,omitempty"`

	Text string `json:"text"`
}
