/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CategorizedTextListInner struct {

	// The identifier of the word
	Id string `json:"id,omitempty"`

	// A note text
	Text string `json:"text"`

	// The descriptive category of the text
	Type_ string `json:"type"`
}
