/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// cross references of a sense
type CrossReferencesListInner struct {

	// The word id of cooccurrence
	Id string `json:"id"`

	// The word of cooccurrence
	Text string `json:"text"`

	// The type of relation between the two words. Possible values are 'close match', 'related', 'see also', 'variant spelling', and 'abbreviation' in case of crossreferences, or 'pre', 'post' in case of collocates.
	Type_ string `json:"type"`
}
