/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A reference to another word that is closely related, might provide additional information about the subject, has a variant spelling or is an abbreviated form of it.
type CrossReferencesList struct {
}
