/* 
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type Entry struct {

	// The origin of the word and the way in which its meaning has changed throughout history
	Etymologies Arrayofstrings `json:"etymologies,omitempty"`

	GrammaticalFeatures GrammaticalFeaturesList `json:"grammaticalFeatures,omitempty"`

	// Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
	HomographNumber string `json:"homographNumber,omitempty"`

	Notes CategorizedTextList `json:"notes,omitempty"`

	Pronunciations PronunciationsList `json:"pronunciations,omitempty"`

	// Complete list of senses
	Senses []Sense `json:"senses,omitempty"`

	// Various words that are used interchangeably depending on the context, e.g 'a' and 'an'
	VariantForms VariantFormsList `json:"variantForms,omitempty"`
}
