/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExamplesListInner struct {

	// A list of statements of the exact meaning of a word
	Definitions *Arrayofstrings `json:"definitions,omitempty"`

	// A subject, discipline, or branch of knowledge particular to the Sense
	Domains *Arrayofstrings `json:"domains,omitempty"`

	Notes *CategorizedTextList `json:"notes,omitempty"`

	// A particular area in which the pronunciation occurs, e.g. 'Great Britain'
	Regions *Arrayofstrings `json:"regions,omitempty"`

	// A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
	Registers *Arrayofstrings `json:"registers,omitempty"`

	// The list of sense identifiers related to the example. Provided in the sentences endpoint only.
	SenseIds *Arrayofstrings `json:"senseIds,omitempty"`

	Text string `json:"text"`

	Translations *TranslationsList `json:"translations,omitempty"`
}
