/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Description of an inflected form of a word
type HeadwordLemmatron struct {

	// The identifier of a word
	Id string `json:"id"`

	// IANA language code
	Language string `json:"language"`

	// A grouping of various senses in a specific language, and a lexical category that relates to a word
	LexicalEntries []LemmatronLexicalEntry `json:"lexicalEntries"`

	// The json object type. Could be 'headword', 'inflection' or 'phrase'
	Type_ string `json:"type,omitempty"`

	// A given written or spoken realisation of a an entry, lowercased.
	Word string `json:"word"`
}
