/* 
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// Description of an inflected form of a word
type HeadwordLemmatron struct {

	// The identifier of a word
	Id string `json:"id,omitempty"`

	// IANA language code
	Language string `json:"language,omitempty"`

	// A grouping of various senses in a specific language, and a lexical category that relates to a word
	LexicalEntries []LemmatronLexicalEntry `json:"lexicalEntries,omitempty"`

	// The json object type. Could be 'headword', 'inflection' or 'phrase'
	Type_ string `json:"type,omitempty"`

	// A given written or spoken realisation of a an entry, lowercased.
	Word string `json:"word,omitempty"`
}
