/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Translation language of the results
type LanguagesTargetLanguage struct {

	// IANA language code
	Id string `json:"id,omitempty"`

	// Language label.
	Language string `json:"language,omitempty"`
}
