/* 
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// Description of an entry for a particular part of speech and grammatical features
type LemmatronLexicalEntry struct {

	GrammaticalFeatures GrammaticalFeaturesList `json:"grammaticalFeatures,omitempty"`

	// The canonical form of words for which the entry is an inflection
	InflectionOf InflectionsList `json:"inflectionOf,omitempty"`

	// IANA language code
	Language string `json:"language,omitempty"`

	// A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
	LexicalCategory string `json:"lexicalCategory,omitempty"`

	// A given written or spoken realisation of a an entry.
	Text string `json:"text,omitempty"`
}
