/* 
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// Description of an entry for a particular part of speech
type LexicalEntry struct {

	// Other words from which this one derives
	DerivativeOf ArrayOfRelatedEntries `json:"derivativeOf,omitempty"`

	// Other words from which their Sense derives
	Derivatives ArrayOfRelatedEntries `json:"derivatives,omitempty"`

	Entries []Entry `json:"entries,omitempty"`

	GrammaticalFeatures GrammaticalFeaturesList `json:"grammaticalFeatures,omitempty"`

	// IANA language code
	Language string `json:"language,omitempty"`

	// A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
	LexicalCategory string `json:"lexicalCategory,omitempty"`

	Notes CategorizedTextList `json:"notes,omitempty"`

	Pronunciations PronunciationsList `json:"pronunciations,omitempty"`

	// A given written or spoken realisation of a an entry.
	Text string `json:"text,omitempty"`

	// Various words that are used interchangeably depending on the context, e.g 'a' and 'an'
	VariantForms VariantFormsList `json:"variantForms,omitempty"`
}
