/* 
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// A grouping of pronunciation information
type PronunciationsListInner struct {

	// The URL of the sound file
	AudioFile string `json:"audioFile,omitempty"`

	// A local or regional variation where the pronunciation occurs, e.g. 'British English'
	Dialects Arrayofstrings `json:"dialects,omitempty"`

	// The alphabetic system used to display the phonetic spelling
	PhoneticNotation string `json:"phoneticNotation,omitempty"`

	// Phonetic spelling is the representation of vocal sounds which express pronunciations of words. It is a system of spelling in which each letter represents invariably the same spoken sound
	PhoneticSpelling string `json:"phoneticSpelling,omitempty"`

	// A particular area in which the pronunciation occurs, e.g. 'Great Britain'
	Regions Arrayofstrings `json:"regions,omitempty"`
}
