/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element
type Sense struct {

	// A grouping of crossreference notes.
	CrossReferenceMarkers *Arrayofstrings `json:"crossReferenceMarkers,omitempty"`

	CrossReferences *CrossReferencesList `json:"crossReferences,omitempty"`

	// A list of statements of the exact meaning of a word
	Definitions *Arrayofstrings `json:"definitions,omitempty"`

	// A subject, discipline, or branch of knowledge particular to the Sense
	Domains *Arrayofstrings `json:"domains,omitempty"`

	Examples *ExamplesList `json:"examples,omitempty"`

	// The id of the sense that is required for the delete procedure
	Id string `json:"id,omitempty"`

	Notes *CategorizedTextList `json:"notes,omitempty"`

	Pronunciations *PronunciationsList `json:"pronunciations,omitempty"`

	// A particular area in which the Sense occurs, e.g. 'Great Britain'
	Regions *Arrayofstrings `json:"regions,omitempty"`

	// A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
	Registers *Arrayofstrings `json:"registers,omitempty"`

	// A list of short statements of the exact meaning of a word
	ShortDefinitions *Arrayofstrings `json:"short_definitions,omitempty"`

	// Ordered list of subsenses of a sense
	Subsenses []Sense `json:"subsenses,omitempty"`

	// Ordered list of links to the Thesaurus Dictionary
	ThesaurusLinks []ThesaurusLink `json:"thesaurusLinks,omitempty"`

	Translations *TranslationsList `json:"translations,omitempty"`

	// Various words that are used interchangeably depending on the context, e.g 'duck' and 'duck boat'
	VariantForms *VariantFormsList `json:"variantForms,omitempty"`
}
