/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SynonymsAntonymsInner struct {
	Domains *Arrayofstrings `json:"domains,omitempty"`

	Id string `json:"id"`

	Language string `json:"language,omitempty"`

	// A particular area in which the Sense occurs, e.g. 'Great Britain'
	Regions *Arrayofstrings `json:"regions,omitempty"`

	// A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
	Registers *Arrayofstrings `json:"registers,omitempty"`

	Text string `json:"text"`
}
