/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ThesaurusEntry struct {

	// Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
	HomographNumber string `json:"homographNumber,omitempty"`

	// Complete list of senses
	Senses []ThesaurusSense `json:"senses,omitempty"`

	// Various words that are used interchangeably depending on the context, e.g 'a' and 'an'
	VariantForms *VariantFormsList `json:"variantForms,omitempty"`
}
