/* 
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element
type ThesaurusSense struct {

	// antonym of word
	Antonyms SynonymsAntonyms `json:"antonyms,omitempty"`

	// A subject, discipline, or branch of knowledge particular to the Sense
	Domains Arrayofstrings `json:"domains,omitempty"`

	Examples ExamplesList `json:"examples,omitempty"`

	// The id of the sense that is required for the delete procedure
	Id string `json:"id,omitempty"`

	// A particular area in which the Sense occurs, e.g. 'Great Britain'
	Regions Arrayofstrings `json:"regions,omitempty"`

	// A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
	Registers Arrayofstrings `json:"registers,omitempty"`

	// subsenses of word
	Subsenses []ThesaurusSense `json:"subsenses,omitempty"`

	// synonym of word
	Synonyms SynonymsAntonyms `json:"synonyms,omitempty"`
}
