/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Various words that are used interchangeably depending on the context, e.g 'aluminium' and 'aluminum'
type VariantFormsList struct {
}
